src/Entity/Projects.php
<?php

namespace App\Entity;

use App\Repository\ProjectsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProjectsRepository::class)
 */
class Projects
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $page_path;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File(
     *     maxSize = "10240k",
     *     mimeTypes = {"image/jpeg"},
     *     mimeTypesMessage = "Proszę załaduj plik w formacje JPEG"
     * )
     */
    private $photo_path;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_public;

    /**
     * @ORM\Column(type="datetime")
     */
    private $modificated_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $uploaded_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $git_path;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPagePath(): ?string
    {
        return $this->page_path;
    }

    public function setPagePath(string $page_path): self
    {
        $this->page_path = $page_path;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->is_public;
    }

    public function setIsPublic(bool $is_public): self
    {
        $this->is_public = $is_public;

        return $this;
    }

    public function getUploadedAt(): ?\DateTimeInterface
    {
        return $this->uploaded_at;
    }

    public function setUploadedAt(\DateTimeInterface $uploaded_at): self
    {
        $this->uploaded_at = $uploaded_at;

        return $this;
    }

    public function getModificatedAt(): ?\DateTimeInterface
    {
        return $this->modificated_at;
    }

    public function setModificatedAt(\DateTimeInterface $modificated_at): self
    {
        $this->modificated_at = $modificated_at;

        return $this;
    }

    public function getPhotoPath(): ?string
    {
        return $this->photo_path;
    }

    public function setPhotoPath(?string $photo_path): self
    {
        $this->photo_path = $photo_path;

        return $this;
    }

    public function getGitPath(): ?string
    {
        return $this->git_path;
    }

    public function setGitPath(?string $git_path): self
    {
        $this->git_path = $git_path;

        return $this;
    }
}

src/Form/ProjectsType.php
<?php

namespace App\Form;

use App\Entity\Projects;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class ProjectsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, ['label' => 'Nom'])
            ->add('page_path', TextType::class, ['label' => 'Adresse du site Web'])
            ->add('git_path', TextType::class, ['label' => 'Adresse du projet sur github'])
            ->add('description', TextType::class, ['label' => 'Description'])
            ->add('photo_path', FileType::class, [
                'data_class' => null,
                'required' => is_null($builder->getData()->getId()),
                'label' => 'Image',
            ])->add('submit', SubmitType::class, [
                'label' => 'Sauvegarder'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Projects::class,
        ]);
    }
}

src/Controller/ProjectsController.php
<?php

namespace App\Controller;

use App\Entity\Projects;
use App\Form\ProjectsType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Filesystem\Filesystem;
use App\Service\ImagesUploadService;
use Symfony\Component\String\Slugger\SluggerInterface;

class ProjectsController extends AbstractController
{
    /**
     * @Route("/admin/projects", name="admin_projects")
     */
    public function index()
    {

        $em = $this->getDoctrine()->getManager();
        $projectsData = $em->getRepository(Projects::class)->findAll();

        return $this->render('projects/index.html.twig', [
            'projectsData' => $projectsData,
        ]);
    }

    /**
     * @Route("/admin/projects/new", name="admin_projects_new")
     * @param Request $request
     * $return \Symfony\Component\HttpFoundation\Response
     */
    public function new(Request $request,  ImagesUploadService $imageUploadService, SluggerInterface $slugger)
    {
        $newProjects = new Projects();
        $form = $this->createForm(ProjectsType::class, $newProjects);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $pictureFileName = $form->get('photo_path')->getData();
            try {
                if ($pictureFileName != null) {
                    $newFileNamePhoto = $imageUploadService->uploadNewImage($pictureFileName,$slugger);
                    $newProjects->setPhotoPath($newFileNamePhoto);
                }

                $newProjects->setIsPublic(0);
                $newProjects->setUploadedAt(new \DateTime());
                $newProjects->setModificatedAt(new \DateTime());
                $em->persist($newProjects);
                $em->flush();
                $this->addFlash('success', 'Projet ajouté');
            } catch (\Exception $e) {
                $this->addFlash('error', 'Une erreur inattendue est survenue');
            }

            return $this->redirectToRoute('admin_projects');
        }


        return $this->render('projects/new.html.twig', [
            'projectsForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/projects/edit/{id}", name="admin_projects_edit")
     * @param Request $request
     * $return \Symfony\Component\HttpFoundation\Response
     */
    public function edit(Request $request, $id, ImagesUploadService $imageUploadService, SluggerInterface $slugger)
    {
        $em = $this->getDoctrine()->getManager();
        $project = $em->getRepository(Projects::class)->find($id);
        $form = $this->createForm(ProjectsType::class, $project);
        $oldFilePath = $project->getPhotoPath();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $pictureFileName = $form->get('photo_path')->getData();

            try {
                if ($pictureFileName != null) {
                    $newFileNamePhoto = $imageUploadService->uploadEditImage($pictureFileName, $oldFilePath,$slugger);
                    $project->setPhotoPath($newFileNamePhoto);
                } else {
                    $project->setPhotoPath($oldFilePath);
                }
                $project->setModificatedAt(new \DateTime());
                $em->persist($project);
                $em->flush();
                $this->addFlash('success', 'Zedytowano projekt');
            } catch (\Exception $e) {
                $this->addFlash('error', 'Wystąpił nieoczekiwany błąd');
            }
            return $this->redirectToRoute('admin_projects');
        }


        return $this->render('projects/new.html.twig', [
            'projectsForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/projects/delete/{id}", name="admin_projects_delete")
     * @param Request $request
     * $return \Symfony\Component\HttpFoundation\Response
     */
    public function delete($id)
    {
        $filesystem = new Filesystem();
        try {
            $em = $this->getDoctrine()->getManager();
            $project = $em->getRepository(Projects::class)->find($id);
            $filesystem->remove(['download/' . $project->getPhotoPath()]);
            $em->remove($project);
            $em->flush();
            $this->addFlash('success', 'Projet supprimé');
        } catch (\Exception $e) {
            $this->addFlash('error', 'Une erreur inattendue s\'est produite lors de la suppression');
        }
        return $this->redirectToRoute('admin_projects');
    }

    /**
     * @Route("/admin/projects/set_visibility/{id}{visibility}", name="admin_projects_set_visibility")
     */
    public function makeVisible($id, $visibility)
    {
        try {
            $em = $this->getDoctrine()->getManager();
            $project = $em->getRepository(Projects::class)->find($id);
            $project->setModificatedAt(new \DateTime());
            $project->setIsPublic($visibility);
            $em->persist($project);
            $em->flush();
            $this->addFlash('success', 'Visibilité mise à jour');
        } catch (\Exception $e) {
            $this->addFlash('error', 'Une erreur inattendue est survenue');
        }
        return $this->redirectToRoute('admin_projects');
    }
}

templates/projects/index.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}
	{{ parent() }}Compétences
{% endblock %}

{% block body %}
	<div class="card-header">
		<i class="fas fa-table mr-1"></i>
		Tableau des projets
		{% if is_granted('ROLE_ADMIN') %}
			<a class="btn btn-info float-right" href="{{ path('admin_projects_new') }}">Ajouter un projet</a>
		{% else %}
			<a class="btn btn-secondary float-right" href="#" data-toggle="tooltip" data-html="true" title="<b>ATTENTION</b><br>Option non disponible pour le client">Ajouter un projet</a>
		{% endif %}
	</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Nom</th>
						<th>Adresse</th>
						<th>Description</th>
						<th style='width: 40px'>Vignette</th>
						<th style='width: 140px'>Date ajoutée</th>
						<th style='width: 140px'>Date de modification</th>
						<th style='width: 20px'></th>
						<th style='width: 20px'></th>
						<th style='width: 15px'></th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th>Nom</th>
						<th>Adresse</th>
						<th>Description</th>
						<th>Vignette</th>
						<th>Date ajouté</th>
						<th>Date de modification</th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</tfoot>
				<tbody>
					{% for project in projectsData %}
						<tr>
							<td>{{ project.name }}</td>
							<td>
								<a href="{{ project.pagePath }}">{{ project.pagePath }}</a>
							</td>
							<td>{{ project.description }}</td>
							<td><img src="{{ asset('download/')}}{{ project.photoPath }}" class="img-fluid img-thumbnail"></td>
							<td>{{ project.uploadedAt|date('d.m.Y H:i:s') }}</td>
							<td>{{ project.modificatedAt|date('d.m.Y H:i:s') }}</td>
							{% if is_granted('ROLE_ADMIN') %}
								<td>
									<a href="{{ path('admin_projects_edit' , { 'id': project.id }) }}" class="btn btn-success">Editer</a>
								</td>
								<td>
									<a href="{{ path('admin_projects_delete' , { 'id': project.id }) }}" class="btn btn-danger">Suprimer</a>
								</td>
								<td>
									{% if project.isPublic == '1' %}
										<input type="checkbox" checked data-toggle="toggle" data-onstyle="outline-success" data-offstyle="outline-danger" onchange="window.location.href='{{ path('admin_projects_set_visibility' , { 'id': project.id , 'visibility' : '0'}) }}'"></td>
								{% else %}
									<input type="checkbox" data-toggle="toggle" data-onstyle="outline-success" data-offstyle="outline-danger" onchange="window.location.href='{{ path('admin_projects_set_visibility' , { 'id': project.id , 'visibility' : '1'}) }}'"></td>
							{% endif %}
						{% else %}
							<td>
								<a href="#" class="btn btn-secondary" data-toggle="tooltip" data-html="true" title="<b>UWAGA</b><br>Opcja niedostępna dla gościa">Editer</a>
							</td>
							<td>
								<a href="#" class="btn btn-secondary" data-toggle="tooltip" data-html="true" title="<b>UWAGA</b><br>Opcja niedostępna dla gościa">Suprimer</a>
							</td>
							<td>
								{% if project.isPublic == '1' %}
									<input type="checkbox" checked data-toggle="toggle" data-onstyle="outline-secondary" data-offstyle="outline-secondary"></td>
							{% else %}
								<input type="checkbox" data-toggle="toggle" data-onstyle="outline-secondary" data-offstyle="outline-secondary"></td>
						{% endif %}
					{% endif %}
				</tbody>
			</tr>
		{% endfor %}
	</tbody>
</table>{% endblock %}

templates/projects/new.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}
	{{ parent() }}Nouvelles compétences
{% endblock %}

{% block body %}
	<div class="card-body">
		RUBRIQUE Compétences
		{% form_theme projectsForm 'bootstrap_4_layout.html.twig' %}
		{{ form_start(projectsForm) }}
		{{ form_row(projectsForm.name) }}
		{{ form_row(projectsForm.page_path) }}
		{{ form_row(projectsForm.git_path) }}
		{{ form_row(projectsForm.description) }}
		{% if projectsForm.photo_path.vars.data != NULL %}
			<img style='width: 440px' src="{{ asset('download/')}}{{ projectsForm.photo_path.vars.data }}">
		{% endif %}
		{{ form_row(projectsForm.photo_path) }}
		{{ form_row(projectsForm.submit) }}
		{{ form_end(projectsForm) }}
	</div>
{% endblock %}